# Useful Commands:
# docker-compose up -d

version: '3.9'

services:
  db:
    image: postgres:16.2-bullseye
    container_name: cathay-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cathay_db
